### ISSUE TITLE
On sources on the multivariate half-normal

### ISSUE THREAD

**Issue by javierdiegof** [araffin/es-with-search-path#1]
Thank you very much for your code, it has been very helpful. I'm stuck on this algorithm because i don't understand clearly whats up with those "half-normal, absolute value" distributions that are used on the paper. I't would help me a lot to know where did you obtained the expected value needed, in your code those are called "E_HALF_NORMAL" and "E_MULTIDIM_NORMAL".

**Comment by araffin** [comment]
Hello,
For the expectation of half normal distribution: [https://en.wikipedia.org/wiki/Half-normal_distribution](https://en.wikipedia.org/wiki/Half-normal_distribution)
For the multivariate, you can refer to page 21 of [The CMA Evolution Strategy: A Tutorial](https://arxiv.org/pdf/1604.00772.pdf)
Also, this factor is present in the original implementations of [CMA-ES](https://www.lri.fr/~hansen/cmaes_inmatlab.html) (the matlab code is also available on [Wikipedia](https://en.wikipedia.org/wiki/CMA-ES))

**Comment by javierdiegof** [comment]
Thank you very much, i will check carefully those sources. I will program the covariance matrix algorithm too, so it is pretty useful stuff.
